annotations: []
smart_annotations: []
nodes:
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: CUST-SRV1
    node_definition: alpine
    parameters: {}
    ram: null
    tags: []
    x: -120
    y: -160
    interfaces:
      - id: i0
        label: eth0
        mac_address: null
        slot: 0
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: CUST1_OSLO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: -480
    y: -200
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: CUST2_BGO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: 200
    y: -200
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n3
    image_definition: null
    label: CUST_CORE_OSLO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: -120
    y: -360
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
      - id: i5
        label: GigabitEthernet5
        mac_address: null
        slot: 4
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n4
    image_definition: null
    label: R1_OSLO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: -320
    y: 120
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
      - id: i5
        label: GigabitEthernet5
        mac_address: null
        slot: 4
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n5
    image_definition: null
    label: ISP1_OSLO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: -320
    y: -80
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n6
    image_definition: null
    label: ISP2_BGO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: 40
    y: -80
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n7
    image_definition: null
    label: R2_BGO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: 40
    y: 120
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
      - id: i5
        label: GigabitEthernet5
        mac_address: null
        slot: 4
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n8
    image_definition: null
    label: RR1_OSLO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: -280
    y: 280
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
      - id: i5
        label: GigabitEthernet5
        mac_address: null
        slot: 4
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n9
    image_definition: null
    label: RR2_BGO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: 0
    y: 280
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
      - id: i5
        label: GigabitEthernet5
        mac_address: null
        slot: 4
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n10
    image_definition: null
    label: CORE1_OSLO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: -320
    y: 480
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n11
    image_definition: null
    label: CORE2_BGO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: 40
    y: 480
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n12
    image_definition: null
    label: PEER1_OSLO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: -320
    y: 640
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration: []
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n13
    image_definition: null
    label: PEER2_BGO
    node_definition: cat8000v
    parameters: {}
    ram: null
    tags: []
    x: 40
    y: 640
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: GigabitEthernet1
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: GigabitEthernet2
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: GigabitEthernet3
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: GigabitEthernet4
        mac_address: null
        slot: 3
        type: physical
links:
  - id: l0
    n1: n0
    n2: n3
    i1: i0
    i2: i1
    conditioning: {}
    label: alpine-0-eth0<->CUST_CORE_OSLO-GigabitEthernet1
  - id: l1
    n1: n3
    n2: n1
    i1: i2
    i2: i1
    conditioning: {}
    label: CUST_CORE_OSLO-GigabitEthernet2<->CUST1_OSLO-GigabitEthernet1
  - id: l2
    n1: n3
    n2: n2
    i1: i3
    i2: i1
    conditioning: {}
    label: CUST_CORE_OSLO-GigabitEthernet3<->CUST2_BGO-GigabitEthernet1
  - id: l3
    n1: n1
    n2: n5
    i1: i2
    i2: i1
    conditioning: {}
    label: CUST1_OSLO-GigabitEthernet2<->ISP1_OSLO-GigabitEthernet1
  - id: l4
    n1: n1
    n2: n4
    i1: i3
    i2: i1
    conditioning: {}
    label: CUST1_OSLO-GigabitEthernet3<->R1_OSLO-GigabitEthernet1
  - id: l5
    n1: n2
    n2: n6
    i1: i2
    i2: i1
    conditioning: {}
    label: CUST2_BGO-GigabitEthernet2<->ISP2_BGO-GigabitEthernet1
  - id: l6
    n1: n2
    n2: n7
    i1: i3
    i2: i1
    conditioning: {}
    label: CUST2_BGO-GigabitEthernet3<->R2_BGO-GigabitEthernet1
  - id: l7
    n1: n5
    n2: n4
    i1: i2
    i2: i2
    conditioning: {}
    label: ISP1_OSLO-GigabitEthernet2<->R1_OSLO-GigabitEthernet2
  - id: l8
    n1: n6
    n2: n7
    i1: i2
    i2: i2
    conditioning: {}
    label: ISP2_BGO-GigabitEthernet2<->R2_BGO-GigabitEthernet2
  - id: l9
    n1: n4
    n2: n6
    i1: i3
    i2: i3
    conditioning: {}
    label: R1_OSLO-GigabitEthernet3<->ISP2_BGO-GigabitEthernet3
  - id: l10
    n1: n7
    n2: n5
    i1: i3
    i2: i3
    conditioning: {}
    label: R2_BGO-GigabitEthernet3<->ISP1_OSLO-GigabitEthernet3
  - id: l11
    n1: n4
    n2: n8
    i1: i4
    i2: i1
    conditioning: {}
    label: R1_OSLO-GigabitEthernet4<->RR1_OSLO-GigabitEthernet1
  - id: l12
    n1: n7
    n2: n9
    i1: i4
    i2: i1
    conditioning: {}
    label: R2_BGO-GigabitEthernet4<->RR2_BGO-GigabitEthernet1
  - id: l13
    n1: n8
    n2: n10
    i1: i2
    i2: i1
    conditioning: {}
    label: RR1_OSLO-GigabitEthernet2<->CORE1_OSLO-GigabitEthernet1
  - id: l14
    n1: n9
    n2: n11
    i1: i2
    i2: i1
    conditioning: {}
    label: RR2_BGO-GigabitEthernet2<->CORE2_BGO-GigabitEthernet1
  - id: l15
    n1: n8
    n2: n7
    i1: i3
    i2: i5
    conditioning: {}
    label: RR1_OSLO-GigabitEthernet3<->R2_BGO-GigabitEthernet5
  - id: l16
    n1: n9
    n2: n4
    i1: i3
    i2: i5
    conditioning: {}
    label: RR2_BGO-GigabitEthernet3<->R1_OSLO-GigabitEthernet5
  - id: l17
    n1: n10
    n2: n9
    i1: i2
    i2: i4
    conditioning: {}
    label: CORE1_OSLO-GigabitEthernet2<->RR2_BGO-GigabitEthernet4
  - id: l18
    n1: n11
    n2: n8
    i1: i2
    i2: i4
    conditioning: {}
    label: CORE2_BGO-GigabitEthernet2<->RR1_OSLO-GigabitEthernet4
  - id: l19
    n1: n10
    n2: n12
    i1: i3
    i2: i1
    conditioning: {}
    label: CORE1_OSLO-GigabitEthernet3<->PEER1_OSLO-GigabitEthernet1
  - id: l20
    n1: n11
    n2: n13
    i1: i3
    i2: i1
    conditioning: {}
    label: CORE2_BGO-GigabitEthernet3<->PEER2_BGO-GigabitEthernet1
  - id: l21
    n1: n10
    n2: n11
    i1: i4
    i2: i4
    conditioning: {}
    label: CORE1_OSLO-GigabitEthernet4<->CORE2_BGO-GigabitEthernet4
  - id: l22
    n1: n8
    n2: n9
    i1: i5
    i2: i5
    conditioning: {}
    label: RR1_OSLO-GigabitEthernet5<->RR2_BGO-GigabitEthernet5
lab:
  description: ''
  notes: ''
  title: 'Project 4 - BGP: SR and TE LAB'
  version: 0.3.0
